#!/bin/sh

umask 022

add_zeros() {
	case "${#1}" in
		1)
			echo "00$1"
		;;
		2)
			echo "0$1"
		;;
		*)
			echo "$1"
		;;
	esac
}

num1=$(echo "$MDEV" | sed -r 's#usbdev([0-9]+).[0-9]+#\1#g')
num2=$(echo "$MDEV" | sed -r 's#usbdev[0-9]+.([0-9]+)#\1#g')
usb_path="usb${num1}"
usb_path="$(find /sys/devices -type d -name "${usb_path}")"
usb_dev_dir="${num1}-${num2}"

bus="$(add_zeros "$num1")"
usb_dev="$(add_zeros "$num2")"

case "$ACTION" in
	'add'|'')
		# Try load needed modules for new usb device.
		test -d "${usb_path}/${usb_dev_dir}" && for modalias in "${usb_path}/${usb_dev_dir}"/*/modalias; do
			modprobe -b -a "$(cat "${modalias}")" 2>/dev/null
		done

		# Move usbdev<num>.<num> to /dev/bus/usb/BUS/DEV
		mkdir -p "bus/usb/${bus}"
		mv "${MDEV}" "bus/usb/${bus}/${usb_dev}"

		# Check if our new device is Android Phone, if so, try change group to 'plugdev'.
		if [ -f "/sys/class/usb_device/${MDEV}/device/product" ]; then
			idVendor="$(cat /sys/class/usb_device/${MDEV}/device/idVendor)"
			case "${idVendor}" in
				# Catch most of the Android Phones.
				'0bb4'|'18d1'|'22b8'|'0fce'|'19d2'|'04e8')
					chgrp 'plugdev' "bus/usb/${bus}/${usb_dev}" 2>/dev/null && chmod 660 "bus/usb/${bus}/${usb_dev}"
				;;
			esac
		fi
	;;
	'remove')
		rm "bus/usb/${bus}/${usb_dev}"
		rmdir "bus/usb/${bus}" 2>/dev/null
		rmdir "bus/usb" 2>/dev/null
	;;
esac
